import React from 'react';
import Head from 'next/head'

export default function Home(): JSX.Element {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
      <h1>
        Patients
      </h1>
    </header>
    <main>
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>ID</th>
            <th>Date of birth</th>
            <th>Registration date</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Firstname Lastname</td>
            <td>abc123</td>
            <td>1st January 1950</td>
            <td>1st January 2020</td>
          </tr>
          <tr>
            <td>Firstname Lastname</td>
            <td>abc123</td>
            <td>1st January 1950</td>
            <td>1st January 2020</td>
          </tr>
          <tr>
            <td>Firstname Lastname</td>
            <td>abc123</td>
            <td>1st January 1950</td>
            <td>1st January 2020</td>
          </tr>
        </tbody>
      </table>
    </main>
    </>
  )
}
