import React, { useEffect, useState } from 'react'
import Head from 'next/head'
import { getAllPatients } from '../services/patientService'
import { Patient } from '../types/patients'
import { GetServerSideProps, InferGetServerSidePropsType } from 'next'
import PatientTable from '../components/PatientTable/PatientTable'

export const getServerSideProps: GetServerSideProps<{
	patientData: Patient[]
}> = async () => {
	const response = await getAllPatients()

	return { props: { patientData: response } }
}

export default function Home({
	patientData,
}: InferGetServerSidePropsType<typeof getServerSideProps>): JSX.Element {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<header>
				<h1>Patients</h1>
			</header>
			<main>
				<PatientTable patientData={patientData} />
			</main>
		</>
	)
}
